/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { CentrosControllerService } from './services/centros-controller.service';
import { CentrosCitasControllerService } from './services/centros-citas-controller.service';
import { CitasControllerService } from './services/citas-controller.service';
import { HistorialControllerService } from './services/historial-controller.service';
import { InventarioControllerService } from './services/inventario-controller.service';
import { ModuloEducativoControllerService } from './services/modulo-educativo-controller.service';
import { NotificacionesControllerService } from './services/notificaciones-controller.service';
import { NotificacionesUsuariosControllerService } from './services/notificaciones-usuarios-controller.service';
import { PingControllerService } from './services/ping-controller.service';
import { UsuariosControllerService } from './services/usuarios-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    CentrosControllerService,
    CentrosCitasControllerService,
    CitasControllerService,
    HistorialControllerService,
    InventarioControllerService,
    ModuloEducativoControllerService,
    NotificacionesControllerService,
    NotificacionesUsuariosControllerService,
    PingControllerService,
    UsuariosControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
