/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { Centros } from './models/centros';
export { CentrosPartial } from './models/centros-partial';
export { CentrosWithRelations } from './models/centros-with-relations';
export { Citas } from './models/citas';
export { CitasPartial } from './models/citas-partial';
export { CitasWithRelations } from './models/citas-with-relations';
export { Historial } from './models/historial';
export { HistorialPartial } from './models/historial-partial';
export { HistorialWithRelations } from './models/historial-with-relations';
export { Inventario } from './models/inventario';
export { InventarioPartial } from './models/inventario-partial';
export { InventarioWithRelations } from './models/inventario-with-relations';
export { Count as LoopbackCount } from './models/loopback/count';
export { ModuloEducativo } from './models/modulo-educativo';
export { ModuloEducativoPartial } from './models/modulo-educativo-partial';
export { ModuloEducativoWithRelations } from './models/modulo-educativo-with-relations';
export { NewCentros } from './models/new-centros';
export { NewCitas } from './models/new-citas';
export { NewCitasInCentros } from './models/new-citas-in-centros';
export { NewHistorial } from './models/new-historial';
export { NewInventario } from './models/new-inventario';
export { NewModuloEducativo } from './models/new-modulo-educativo';
export { NewNotificaciones } from './models/new-notificaciones';
export { NewUsuarios } from './models/new-usuarios';
export { Notificaciones } from './models/notificaciones';
export { NotificacionesPartial } from './models/notificaciones-partial';
export { NotificacionesWithRelations } from './models/notificaciones-with-relations';
export { PingResponse } from './models/ping-response';
export { Usuarios } from './models/usuarios';
export { UsuariosPartial } from './models/usuarios-partial';
export { UsuariosWithRelations } from './models/usuarios-with-relations';
