/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CentrosControllerService } from './services/centros-controller.service';
export { CentrosCitasControllerService } from './services/centros-citas-controller.service';
export { CitasControllerService } from './services/citas-controller.service';
export { HistorialControllerService } from './services/historial-controller.service';
export { InventarioControllerService } from './services/inventario-controller.service';
export { ModuloEducativoControllerService } from './services/modulo-educativo-controller.service';
export { NotificacionesControllerService } from './services/notificaciones-controller.service';
export { NotificacionesUsuariosControllerService } from './services/notificaciones-usuarios-controller.service';
export { PingControllerService } from './services/ping-controller.service';
export { UsuariosControllerService } from './services/usuarios-controller.service';
