/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CitasWithRelations } from '../models/citas-with-relations';

/**
 * (tsType: CentrosWithRelations, schemaOptions: { includeRelations: true })
 */
export interface CentrosWithRelations {
  citas?: Array<CitasWithRelations>;
  correo: string;
  direccion: string;
  horario_atencion: string;
  id?: string;
  nombre: string;
  telefono: string;
  ubicacion: {
};
}
