/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Partial<Centros>, schemaOptions: { partial: true })
 */
export interface CentrosPartial {
  correo?: string;
  direccion?: string;
  horario_atencion?: string;
  id?: string;
  nombre?: string;
  telefono?: string;
  ubicacion?: {
};
}
