/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Centros {
  correo: string;
  direccion: string;
  horario_atencion: string;
  id?: string;
  nombre: string;
  telefono: string;
  ubicacion: {
};
}
