/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Partial<Citas>, schemaOptions: { partial: true })
 */
export interface CitasPartial {
  centro?: string;
  centrosId?: string;
  estado?: string;
  fecha?: string;
  hora?: string;
  id?: string;
  id_centro?: string;
  id_usuario?: string;
  usuario?: string;
}
