/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: CitasWithRelations, schemaOptions: { includeRelations: true })
 */
export interface CitasWithRelations {
  centro?: string;
  centrosId?: string;
  estado: string;
  fecha: string;
  foreignKey?: any;
  hora: string;
  id?: string;
  id_centro: string;
  id_usuario: string;
  usuario?: string;
}
