/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Citas {
  centro?: string;
  centrosId?: string;
  estado: string;
  fecha: string;
  hora: string;
  id?: string;
  id_centro: string;
  id_usuario: string;
  usuario?: string;
}
