/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: HistorialWithRelations, schemaOptions: { includeRelations: true })
 */
export interface HistorialWithRelations {
  cantidad: number;
  descripcion: string;
  fecha: string;
  id?: string;
  id_centro: string;
  id_usuario: string;
  tipoMovimiento: string;
  tipoSangre: string;
}
