/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Historial {
  cantidad: number;
  descripcion: string;
  fecha: string;
  id?: string;
  id_centro: string;
  id_usuario: string;
  tipoMovimiento: string;
  tipoSangre: string;
}
