/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: InventarioWithRelations, schemaOptions: { includeRelations: true })
 */
export interface InventarioWithRelations {
  cantidad: number;
  fechaUltimaActualizacion: string;
  id?: string;
  id_centro: string;
  tipoSangre: string;
}
