/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Inventario {
  cantidad: number;
  fechaUltimaActualizacion: string;
  id?: string;
  id_centro: string;
  tipoSangre: string;
}
