/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Partial<Inventario>, schemaOptions: { partial: true })
 */
export interface InventarioPartial {
  cantidad?: number;
  fechaUltimaActualizacion?: string;
  id?: string;
  id_centro?: string;
  tipoSangre?: string;
}
