/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModuloEducativo {
  categoria: string;
  contenido: string;
  fecha_publicacion: string;
  id?: string;
}
