/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Partial<ModuloEducativo>, schemaOptions: { partial: true })
 */
export interface ModuloEducativoPartial {
  categoria?: string;
  contenido?: string;
  fecha_publicacion?: string;
  id?: string;
}
