/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: ModuloEducativoWithRelations, schemaOptions: { includeRelations: true })
 */
export interface ModuloEducativoWithRelations {
  categoria: string;
  contenido: string;
  fecha_publicacion: string;
  id?: string;
}
