/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Omit<ModuloEducativo, 'id'>, schemaOptions: { title: 'NewModuloEducativo', exclude: [ 'id' ] })
 */
export interface NewModuloEducativo {
  categoria: string;
  contenido: string;
  fecha_publicacion: string;
}
