/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<Citas, 'id'>, 'centrosId'>, schemaOptions: { title: 'NewCitasInCentros', exclude: [ 'id' ], optional: [ 'centrosId' ] })
 */
export interface NewCitasInCentros {
  centro?: string;
  centrosId?: string;
  estado: string;
  fecha: string;
  hora: string;
  id_centro: string;
  id_usuario: string;
  usuario?: string;
}
