/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Omit<Historial, 'id'>, schemaOptions: { title: 'NewHistorial', exclude: [ 'id' ] })
 */
export interface NewHistorial {
  cantidad: number;
  descripcion: string;
  fecha: string;
  id_centro: string;
  id_usuario: string;
  tipoMovimiento: string;
  tipoSangre: string;
}
