/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Omit<Usuarios, 'id'>, schemaOptions: { title: 'NewUsuarios', exclude: [ 'id' ] })
 */
export interface NewUsuarios {
  apellido: string;
  celular: string;
  correo: string;
  direccion: string;
  fecha_registro: string;
  nombre: string;
  rol: string;
  tipo_sangre: string;
}
