/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Omit<Inventario, 'id'>, schemaOptions: { title: 'NewInventario', exclude: [ 'id' ] })
 */
export interface NewInventario {
  cantidad: number;
  fechaUltimaActualizacion: string;
  id_centro: string;
  tipoSangre: string;
}
