/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Omit<Citas, 'id'>, schemaOptions: { title: 'NewCitas', exclude: [ 'id' ] })
 */
export interface NewCitas {
  centro?: string;
  centrosId?: string;
  estado: string;
  fecha: string;
  hora: string;
  id_centro: string;
  id_usuario: string;
  usuario?: string;
}
