/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Omit<Notificaciones, 'id'>, schemaOptions: { title: 'NewNotificaciones', exclude: [ 'id' ] })
 */
export interface NewNotificaciones {
  fecha_envio: string;
  id_usuario: string;
  mensaje: string;
  tipo: string;
  usuario?: string;
  usuariosId?: string;
}
