/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Omit<Centros, 'id'>, schemaOptions: { title: 'NewCentros', exclude: [ 'id' ] })
 */
export interface NewCentros {
  correo: string;
  direccion: string;
  horario_atencion: string;
  nombre: string;
  telefono: string;
  ubicacion: {
};
}
