/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * (tsType: Partial<Notificaciones>, schemaOptions: { partial: true })
 */
export interface NotificacionesPartial {
  fecha_envio?: string;
  id?: string;
  id_usuario?: string;
  mensaje?: string;
  tipo?: string;
  usuario?: string;
  usuariosId?: string;
}
