/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuariosWithRelations } from '../models/usuarios-with-relations';

/**
 * (tsType: NotificacionesWithRelations, schemaOptions: { includeRelations: true })
 */
export interface NotificacionesWithRelations {
  fecha_envio: string;
  foreignKey?: any;
  id?: string;
  id_usuario: string;
  mensaje: string;
  tipo: string;
  usuario?: string;
  usuarios?: UsuariosWithRelations;
  usuariosId?: string;
}
