/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Notificaciones {
  fecha_envio: string;
  id?: string;
  id_usuario: string;
  mensaje: string;
  tipo: string;
  usuario?: string;
  usuariosId?: string;
}
