/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PingResponse {
  date?: string;
  greeting?: string;
  headers?: {
'Content-Type'?: string;
[key: string]: any;
};
  url?: string;
}
