/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Usuarios {
  apellido: string;
  celular: string;
  correo: string;
  direccion: string;
  fecha_registro: string;
  id?: string;
  nombre: string;
  rol: string;
  tipo_sangre: string;
}
