/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CitasWithRelations } from '../models/citas-with-relations';
import { NotificacionesWithRelations } from '../models/notificaciones-with-relations';

/**
 * (tsType: UsuariosWithRelations, schemaOptions: { includeRelations: true })
 */
export interface UsuariosWithRelations {
  apellido: string;
  celular: string;
  citas?: Array<CitasWithRelations>;
  correo: string;
  direccion: string;
  fecha_registro: string;
  id?: string;
  nombre: string;
  notificaciones?: Array<NotificacionesWithRelations>;
  rol: string;
  tipo_sangre: string;
}
