/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Citas } from '../models/citas';
import { create } from '../fn/centros-citas-controller/create';
import { Create$Params } from '../fn/centros-citas-controller/create';
import { delete$ } from '../fn/centros-citas-controller/delete';
import { Delete$Params } from '../fn/centros-citas-controller/delete';
import { find } from '../fn/centros-citas-controller/find';
import { Find$Params } from '../fn/centros-citas-controller/find';
import { Count as LoopbackCount } from '../models/loopback/count';
import { patch } from '../fn/centros-citas-controller/patch';
import { Patch$Params } from '../fn/centros-citas-controller/patch';

@Injectable({ providedIn: 'root' })
export class CentrosCitasControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `centrosCitasControllerFind()` */
  static readonly CentrosCitasControllerFindPath = '/centros/{id}/citas';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `find()` instead.
   *
   * This method doesn't expect any request body.
   */
  find$Response(params: Find$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Citas>>> {
    return find(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `find$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  find(params: Find$Params, context?: HttpContext): Observable<Array<Citas>> {
    return this.find$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Citas>>): Array<Citas> => r.body)
    );
  }

  /** Path part for operation `centrosCitasControllerCreate()` */
  static readonly CentrosCitasControllerCreatePath = '/centros/{id}/citas';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<Citas>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<Citas> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<Citas>): Citas => r.body)
    );
  }

  /** Path part for operation `centrosCitasControllerDelete()` */
  static readonly CentrosCitasControllerDeletePath = '/centros/{id}/citas';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<LoopbackCount>> {
    return delete$(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<LoopbackCount> {
    return this.delete$Response(params, context).pipe(
      map((r: StrictHttpResponse<LoopbackCount>): LoopbackCount => r.body)
    );
  }

  /** Path part for operation `centrosCitasControllerPatch()` */
  static readonly CentrosCitasControllerPatchPath = '/centros/{id}/citas';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `patch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  patch$Response(params: Patch$Params, context?: HttpContext): Observable<StrictHttpResponse<LoopbackCount>> {
    return patch(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `patch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  patch(params: Patch$Params, context?: HttpContext): Observable<LoopbackCount> {
    return this.patch$Response(params, context).pipe(
      map((r: StrictHttpResponse<LoopbackCount>): LoopbackCount => r.body)
    );
  }

}
