/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getUsuarios } from '../fn/notificaciones-usuarios-controller/get-usuarios';
import { GetUsuarios$Params } from '../fn/notificaciones-usuarios-controller/get-usuarios';
import { Usuarios } from '../models/usuarios';

@Injectable({ providedIn: 'root' })
export class NotificacionesUsuariosControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `notificacionesUsuariosControllerGetUsuarios()` */
  static readonly NotificacionesUsuariosControllerGetUsuariosPath = '/notificaciones/{id}/usuarios';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsuarios()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuarios$Response(params: GetUsuarios$Params, context?: HttpContext): Observable<StrictHttpResponse<Usuarios>> {
    return getUsuarios(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsuarios$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsuarios(params: GetUsuarios$Params, context?: HttpContext): Observable<Usuarios> {
    return this.getUsuarios$Response(params, context).pipe(
      map((r: StrictHttpResponse<Usuarios>): Usuarios => r.body)
    );
  }

}
